on: [push, pull_request]
name: build

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-gnu
            archive-name: extern_c_test-linux.tar.gz
          - build: macos
            os: macos-latest
            rust: nightly
            target: x86_64-apple-darwin
            archive-name: extern_c_test-macos.tar.gz
          - build: windows
            os: windows-2019
            rust: nightly-x86_64-msvc
            target: x86_64-pc-windows-msvc
            archive-name: extern_c_test-windows.7z
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      
      - name: install openssl-tools
        if: matrix.build == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install libssl-dev cmake pkg-config musl-tools

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }} 
        env:
          RUST_BACKTRACE: 1

      - name: Strip binary (macos)
        if: matrix.build == 'macos'
        run: |
          strip "target/${{ matrix.target }}/release/libextern_c_test.dylib"

      - name: Strip binary (linux)
        if: matrix.build == 'linux'
        run: |
          strip "target/${{ matrix.target }}/release/libextern_c_test.so"

      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cd archive
          if [ "${{ matrix.build }}" = "windows" ]; then
            cp "../target/${{ matrix.target }}/release/extern_c_test.dll" ./extern_c_test.dll
            cp "../prime.h" ./prime.h
            7z a "${{ matrix.archive-name }}" extern_c_test.dll prime.h
          elif [ "${{ matrix.build }}" = "macos" ]; then
            cp "../target/${{ matrix.target }}/release/libextern_c_test.dylib" ./libextern_c_test.dylib
            cp "../prime.h" ./prime.h
            tar -czf "${{ matrix.archive-name }}" libextern_c_test.dylib prime.h
          else 
            cp "../target/${{ matrix.target }}/release/libextern_c_test.so" ./libextern_c_test.so
            cp "../prime.h" ./prime.h
            tar -czf "${{ matrix.archive-name }}" libextern_c_test.so prime.h
          fi
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive-name }}
          path: archive/${{ matrix.archive-name }}

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if: ${{ startsWith(github.ref, 'refs/heads/main') }}
  #   needs: [build]
  #   permissions:
  #     # Use to sign the release artifacts
  #     id-token: write
  #     # Used to upload release artifacts
  #     contents: write
  #     # Used to generate artifact attestation
  #     attestations: write
  #   steps:
  #     - uses: actions/download-artifact@v4
  #     - name: Display structure of downloaded files
  #       run: ls -R
  #     - name: pwd
  #       run: pwd
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-path: 'wheels-*/*'
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       /home/runner/work/extern_c_test/extern_c_test/extern_c_test-linux.tar.gz
      #       /home/runner/work/extern_c_test/extern_c_test/extern_c_test-macos.tar.gz
      #       /home/runner/work/extern_c_test/extern_c_test/extern_c_test-windows.7z
      #     draft: true
      #     fail_on_unmatched_files: true
